language: python

python:
 - 3.6

env:
 - DJANGO=2.1.4

before_install:
 - export DJANGO_SETTINGS_MODULE=canteenWeb.settings

install:
 - pip install -r requirements.txt

before_script:
 - python3 manage.py makemigrations
 - python3 manage.py migrate

script:
 - black .
 - python3 manage.py test
